"""Assessment service — re-export shim.

All implementations have been moved to focused modules:
  - assessment_crud.py   (CRUD + lifecycle)
  - attempt_service.py   (student attempt flow)
  - review_service.py    (teacher review queue)
  - _shared.py           (private helpers)
"""

from src.services.assessments._shared import (
    _ACTIVITY_TO_KIND,
    _ALLOWED_LIFECYCLE_TRANSITIONS,
    _KIND_TO_ACTIVITY,
    _REVIEW_SORT_MAP,
    _UNSET,
    ASSESSABLE_ACTIVITY_TYPES,
    _active_policy_override,
    _assert_attempt_action_allowed,
    _batch_fetch_users,
    _build_assessment_read,
    _build_attempt_projection,
    _build_attempt_state,
    _build_item_read,
    _build_override_read,
    _build_policy_read,
    _build_review_projection,
    _build_student_submission_read,
    _build_teacher_submission_read,
    _coerce_datetime,
    _content_version,
    _default_activity_settings,
    _default_anti_cheat,
    _default_completion_rule,
    _default_grading_mode,
    _dt_iso,
    _earliest_datetime,
    _effective_due_at,
    _enforce_draft_version,
    _ensure_authorable,
    _first_int_setting,
    _first_string_setting,
    _get_activity_and_course,
    _get_activity_by_uuid_or_404,
    _get_assessment_by_uuid_or_404,
    _get_assessment_submission_or_404,
    _get_chapter_or_404,
    _get_course_for_activity_or_404,
    _get_course_or_404,
    _get_item_or_404,
    _get_items,
    _get_items_raw,
    _get_or_create_policy,
    _get_or_create_submission_draft,
    _get_or_project_assessment_for_activity,
    _get_policy_for_assessment,
    _has_published_grade,
    _has_submit_access,
    _is_result_visible,
    _item_readiness_issues,
    _normalize_answer_patch,
    _normalize_policy_settings_json,
    _normalized_policy_patch,
    _parse_if_match_version,
    _policy_version,
    _release_state_for_submission,
    _require_author,
    _require_grade,
    _require_publish,
    _require_read,
    _require_submit_access,
    _score_projection_from_submission,
    _snapshot_submission,
    _submission_user,
    _sync_activity_lifecycle,
    _time_limit_seconds_from_settings,
    build_readiness,
)
from src.services.assessments.assessment_crud import (
    check_publish_readiness,
    create_assessment,
    create_assessment_item,
    delete_assessment_item,
    duplicate_assessment,
    get_assessment,
    get_assessment_by_activity_uuid,
    reorder_assessment_items,
    transition_assessment_lifecycle,
    update_assessment,
    update_assessment_item,
)
from src.services.assessments.attempt_service import (
    get_attempt_state,
    get_code_item_run,
    get_my_assessment_draft,
    get_my_assessment_submissions,
    run_code_item,
    save_assessment_draft,
    save_grading_draft,
    start_assessment,
    submit_assessment,
)
from src.services.assessments.review_service import (
    create_student_policy_override,
    delete_student_policy_override,
    get_assessment_submission,
    get_assessment_submission_stats,
    get_assessment_submissions,
    get_policy_preset,
    list_student_policy_overrides,
    publish_assessment_grades,
    save_assessment_grade,
    update_student_policy_override,
)

__all__ = [
    "ASSESSABLE_ACTIVITY_TYPES",
    "build_readiness",
    "check_publish_readiness",
    "create_assessment",
    "create_assessment_item",
    "create_student_policy_override",
    "delete_assessment_item",
    "delete_student_policy_override",
    "get_assessment",
    "get_assessment_by_activity_uuid",
    "get_assessment_submission",
    "get_assessment_submission_stats",
    "get_assessment_submissions",
    "get_attempt_state",
    "get_code_item_run",
    "get_my_assessment_draft",
    "get_my_assessment_submissions",
    "get_policy_preset",
    "list_student_policy_overrides",
    "publish_assessment_grades",
    "reorder_assessment_items",
    "run_code_item",
    "save_assessment_draft",
    "save_assessment_grade",
    "save_grading_draft",
    "start_assessment",
    "submit_assessment",
    "transition_assessment_lifecycle",
    "update_assessment",
    "update_assessment_item",
    "update_student_policy_override",
]
