export type EmbedCategoryId =
  | 'visual'
  | 'code'
  | 'media'
  | 'assessment'
  | 'productivity'
  | 'academic'
  | 'collaboration';

export interface EmbedCategory {
  id: EmbedCategoryId;
  label: string;
  description: string;
}

export const EMBED_CATEGORIES: EmbedCategory[] = [
  {
    id: 'visual',
    label: 'Visual design',
    description: 'Boards, diagrams, prototypes, canvases, 3D, and animation.',
  },
  {
    id: 'code',
    label: 'Coding',
    description: 'Runnable sandboxes, snippets, full IDEs, and remixable apps.',
  },
  {
    id: 'media',
    label: 'Media',
    description: 'Video, audio, podcasts, playlists, and recorded tutorials.',
  },
  {
    id: 'assessment',
    label: 'Assessments',
    description: 'Quizzes, forms, flashcards, polls, and interactive checks.',
  },
  {
    id: 'productivity',
    label: 'Productivity',
    description: 'Docs, databases, work boards, data tables, and dashboards.',
  },
  {
    id: 'academic',
    label: 'Academic',
    description: 'Math, science, simulations, 3D models, and computation.',
  },
  {
    id: 'collaboration',
    label: 'AI & community',
    description: 'Research spaces, co-browsing, and course community entry points.',
  },
];

export interface EmbedProvider {
  type: string;
  label: string;
  category: EmbedCategoryId;
  description: string;
  placeholder: string;
  hostnames: readonly string[];
  defaultHeight: number;
  allow?: string;
  requiresEmbedUrl?: boolean;
}

export const EMBED_PROVIDERS = [
  {
    type: 'excalidraw',
    label: 'Excalidraw',
    category: 'visual',
    description: 'Hand-drawn diagrams and brainstorming boards.',
    placeholder: 'https://excalidraw.com/#room=...',
    hostnames: ['excalidraw.com'],
    defaultHeight: 520,
  },
  {
    type: 'tldraw',
    label: 'tldraw',
    category: 'visual',
    description: 'Fast infinite canvas for sketches and visual thinking.',
    placeholder: 'https://tldraw.com/r/room-id',
    hostnames: ['tldraw.com'],
    defaultHeight: 520,
  },
  {
    type: 'figma',
    label: 'Figma',
    category: 'visual',
    description: 'Live design files and clickable prototypes.',
    placeholder: 'https://www.figma.com/file/...',
    hostnames: ['figma.com', 'www.figma.com'],
    defaultHeight: 560,
  },
  {
    type: 'canva',
    label: 'Canva',
    category: 'visual',
    description: 'Posters, infographics, presentations, and design assets.',
    placeholder: 'https://www.canva.com/design/...',
    hostnames: ['canva.com', 'www.canva.com'],
    defaultHeight: 560,
  },
  {
    type: 'miro',
    label: 'Miro',
    category: 'visual',
    description: 'Collaborative workshops, mapping, and group boards.',
    placeholder: 'https://miro.com/app/board/...',
    hostnames: ['miro.com', 'www.miro.com'],
    defaultHeight: 560,
  },
  {
    type: 'mural',
    label: 'Mural',
    category: 'visual',
    description: 'Enterprise visual collaboration and workshop canvases.',
    placeholder: 'https://app.mural.co/...',
    hostnames: ['mural.co', 'app.mural.co'],
    defaultHeight: 560,
  },
  {
    type: 'spline',
    label: 'Spline',
    category: 'visual',
    description: 'Interactive 3D scenes and objects.',
    placeholder: 'https://my.spline.design/...',
    hostnames: ['spline.design', 'my.spline.design'],
    defaultHeight: 560,
  },
  {
    type: 'lottiefiles',
    label: 'LottieFiles',
    category: 'visual',
    description: 'Lightweight animations for explainers and feedback.',
    placeholder: 'https://lottiefiles.com/...',
    hostnames: ['lottiefiles.com', 'www.lottiefiles.com'],
    defaultHeight: 420,
  },
  {
    type: 'sketchpad',
    label: 'Sketchpad',
    category: 'visual',
    description: 'Simple browser sketching canvas for quick drawings.',
    placeholder: 'https://sketchpad.app/...',
    hostnames: ['sketchpad.app', 'www.sketchpad.app'],
    defaultHeight: 520,
  },
  {
    type: 'jsfiddle',
    label: 'JSFiddle',
    category: 'code',
    description: 'Quick HTML, CSS, and JavaScript examples.',
    placeholder: 'https://jsfiddle.net/...',
    hostnames: ['jsfiddle.net'],
    defaultHeight: 460,
    requiresEmbedUrl: true,
  },
  {
    type: 'codepen',
    label: 'CodePen',
    category: 'code',
    description: 'Visual front-end demos and interactive pens.',
    placeholder: 'https://codepen.io/user/pen/...',
    hostnames: ['codepen.io'],
    defaultHeight: 460,
  },
  {
    type: 'replit',
    label: 'Replit',
    category: 'code',
    description: 'Full interactive IDEs for many programming languages.',
    placeholder: 'https://replit.com/@user/repl-name',
    hostnames: ['replit.com'],
    defaultHeight: 560,
  },
  {
    type: 'stackblitz',
    label: 'StackBlitz',
    category: 'code',
    description: 'Full-stack web project sandboxes.',
    placeholder: 'https://stackblitz.com/edit/...',
    hostnames: ['stackblitz.com'],
    defaultHeight: 560,
  },
  {
    type: 'github-gist',
    label: 'GitHub Gist',
    category: 'code',
    description: 'Clean code snippets with syntax highlighting.',
    placeholder: 'https://gist.github.com/user/id',
    hostnames: ['gist.github.com'],
    defaultHeight: 420,
  },
  {
    type: 'glitch',
    label: 'Glitch',
    category: 'code',
    description: 'Remixable web apps and project demos.',
    placeholder: 'https://glitch.com/edit/#!/project',
    hostnames: ['glitch.com'],
    defaultHeight: 560,
  },
  {
    type: 'codesnip',
    label: 'CodeSnip',
    category: 'code',
    description: 'Modern snippets with AI explanations.',
    placeholder: 'https://codesnip.dev/...',
    hostnames: ['codesnip.dev', 'www.codesnip.dev'],
    defaultHeight: 460,
  },
  {
    type: 'codesandbox',
    label: 'CodeSandbox',
    category: 'code',
    description: 'Complex front-end architectures and templates.',
    placeholder: 'https://codesandbox.io/p/sandbox/...',
    hostnames: ['codesandbox.io'],
    defaultHeight: 560,
  },
  {
    type: 'youtube',
    label: 'YouTube',
    category: 'media',
    description: 'Educational videos, lectures, and screencasts.',
    placeholder: 'https://www.youtube.com/watch?v=...',
    hostnames: ['youtube.com', 'www.youtube.com', 'youtu.be'],
    defaultHeight: 420,
    allow: 'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share',
  },
  {
    type: 'vimeo',
    label: 'Vimeo',
    category: 'media',
    description: 'High-quality hosted video and private course media.',
    placeholder: 'https://vimeo.com/...',
    hostnames: ['vimeo.com', 'www.vimeo.com', 'player.vimeo.com'],
    defaultHeight: 420,
    allow: 'autoplay; fullscreen; picture-in-picture',
  },
  {
    type: 'loom',
    label: 'Loom',
    category: 'media',
    description: 'Recorded walkthroughs and talking-head tutorials.',
    placeholder: 'https://www.loom.com/share/...',
    hostnames: ['loom.com', 'www.loom.com'],
    defaultHeight: 420,
  },
  {
    type: 'google-vids',
    label: 'Google Vids',
    category: 'media',
    description: 'AI-assisted educational videos and slide-videos.',
    placeholder: 'https://vids.google.com/...',
    hostnames: ['vids.google.com', 'drive.google.com'],
    defaultHeight: 480,
  },
  {
    type: 'wistia',
    label: 'Wistia',
    category: 'media',
    description: 'Course video with analytics and engagement tooling.',
    placeholder: 'https://fast.wistia.net/embed/iframe/...',
    hostnames: ['wistia.com', 'fast.wistia.net'],
    defaultHeight: 420,
  },
  {
    type: 'spotify',
    label: 'Spotify',
    category: 'media',
    description: 'Podcasts and curated study playlists.',
    placeholder: 'https://open.spotify.com/...',
    hostnames: ['open.spotify.com', 'spotify.com'],
    defaultHeight: 352,
  },
  {
    type: 'soundcloud',
    label: 'SoundCloud',
    category: 'media',
    description: 'Audio examples, music lessons, and listening tasks.',
    placeholder: 'https://soundcloud.com/...',
    hostnames: ['soundcloud.com', 'w.soundcloud.com'],
    defaultHeight: 320,
  },
  {
    type: 'suno',
    label: 'Suno',
    category: 'media',
    description: 'AI-generated songs and creative audio assignments.',
    placeholder: 'https://suno.com/song/...',
    hostnames: ['suno.com', 'www.suno.com'],
    defaultHeight: 420,
  },
  {
    type: 'sodaphonic',
    label: 'Sodaphonic',
    category: 'media',
    description: 'Browser audio editor for podcasting modules.',
    placeholder: 'https://sodaphonic.com/...',
    hostnames: ['sodaphonic.com', 'www.sodaphonic.com'],
    defaultHeight: 520,
  },
  {
    type: 'h5p',
    label: 'H5P',
    category: 'assessment',
    description: 'Interactive LMS content such as quizzes and drag-and-drop tasks.',
    placeholder: 'https://h5p.org/h5p/embed/...',
    hostnames: ['h5p.org', 'h5p.com'],
    defaultHeight: 560,
  },
  {
    type: 'genially',
    label: 'Genially',
    category: 'assessment',
    description: 'Gamified presentations and interactive images.',
    placeholder: 'https://view.genially.com/...',
    hostnames: ['genially.com', 'view.genially.com'],
    defaultHeight: 560,
  },
  {
    type: 'typeform',
    label: 'Typeform',
    category: 'assessment',
    description: 'High-engagement surveys and entry or exit tickets.',
    placeholder: 'https://form.typeform.com/to/...',
    hostnames: ['typeform.com', 'form.typeform.com'],
    defaultHeight: 560,
  },
  {
    type: 'jotform',
    label: 'Jotform',
    category: 'assessment',
    description: 'Forms with logic, uploads, and payment workflows.',
    placeholder: 'https://form.jotform.com/...',
    hostnames: ['jotform.com', 'form.jotform.com'],
    defaultHeight: 560,
  },
  {
    type: 'google-forms',
    label: 'Google Forms',
    category: 'assessment',
    description: 'Quick data-driven quizzes and course surveys.',
    placeholder: 'https://docs.google.com/forms/d/e/...',
    hostnames: ['docs.google.com'],
    defaultHeight: 640,
  },
  {
    type: 'tally',
    label: 'Tally',
    category: 'assessment',
    description: 'Notion-style forms that feel lightweight in lessons.',
    placeholder: 'https://tally.so/r/...',
    hostnames: ['tally.so'],
    defaultHeight: 560,
  },
  {
    type: 'quizlet',
    label: 'Quizlet',
    category: 'assessment',
    description: 'Flashcard sets and study games.',
    placeholder: 'https://quizlet.com/...',
    hostnames: ['quizlet.com', 'www.quizlet.com'],
    defaultHeight: 500,
  },
  {
    type: 'kahoot',
    label: 'Kahoot!',
    category: 'assessment',
    description: 'Competitive live assessments and game-based checks.',
    placeholder: 'https://create.kahoot.it/share/...',
    hostnames: ['kahoot.it', 'create.kahoot.it'],
    defaultHeight: 500,
  },
  {
    type: 'mentimeter',
    label: 'Mentimeter',
    category: 'assessment',
    description: 'Live polls, word clouds, and classroom feedback.',
    placeholder: 'https://www.mentimeter.com/...',
    hostnames: ['mentimeter.com', 'www.mentimeter.com'],
    defaultHeight: 560,
  },
  {
    type: 'airtable',
    label: 'Airtable',
    category: 'productivity',
    description: 'Database-driven lessons and project trackers.',
    placeholder: 'https://airtable.com/embed/...',
    hostnames: ['airtable.com'],
    defaultHeight: 560,
  },
  {
    type: 'google-sheets',
    label: 'Google Sheets',
    category: 'productivity',
    description: 'Live tables, datasets, and charts.',
    placeholder: 'https://docs.google.com/spreadsheets/d/...',
    hostnames: ['docs.google.com'],
    defaultHeight: 560,
  },
  {
    type: 'trello',
    label: 'Trello',
    category: 'productivity',
    description: 'Project management boards and course milestones.',
    placeholder: 'https://trello.com/b/...',
    hostnames: ['trello.com'],
    defaultHeight: 560,
  },
  {
    type: 'notion',
    label: 'Notion',
    category: 'productivity',
    description: 'Resource pages, course wikis, and structured docs.',
    placeholder: 'https://www.notion.so/...',
    hostnames: ['notion.so', 'www.notion.so'],
    defaultHeight: 560,
  },
  {
    type: 'coda',
    label: 'Coda',
    category: 'productivity',
    description: 'Interactive docs that behave like apps.',
    placeholder: 'https://coda.io/embed/...',
    hostnames: ['coda.io'],
    defaultHeight: 560,
  },
  {
    type: 'tableau',
    label: 'Tableau',
    category: 'productivity',
    description: 'Advanced analytics dashboards and data visualization.',
    placeholder: 'https://public.tableau.com/views/...',
    hostnames: ['public.tableau.com', 'tableau.com'],
    defaultHeight: 640,
  },
  {
    type: 'desmos',
    label: 'Desmos',
    category: 'academic',
    description: 'Interactive graphing calculator for math.',
    placeholder: 'https://www.desmos.com/calculator/...',
    hostnames: ['desmos.com', 'www.desmos.com'],
    defaultHeight: 520,
  },
  {
    type: 'geogebra',
    label: 'GeoGebra',
    category: 'academic',
    description: 'Geometry, graphing, and 3D math simulations.',
    placeholder: 'https://www.geogebra.org/m/...',
    hostnames: ['geogebra.org', 'www.geogebra.org'],
    defaultHeight: 560,
  },
  {
    type: 'wolfram-alpha',
    label: 'Wolfram Alpha',
    category: 'academic',
    description: 'Computational intelligence and symbolic widgets.',
    placeholder: 'https://www.wolframalpha.com/...',
    hostnames: ['wolframalpha.com', 'www.wolframalpha.com'],
    defaultHeight: 500,
  },
  {
    type: 'phet',
    label: 'PhET',
    category: 'academic',
    description: 'Science simulations for physics, chemistry, and biology.',
    placeholder: 'https://phet.colorado.edu/sims/html/...',
    hostnames: ['phet.colorado.edu'],
    defaultHeight: 620,
  },
  {
    type: 'sketchfab',
    label: 'Sketchfab',
    category: 'academic',
    description: 'Interactive 3D models for artifacts, anatomy, and objects.',
    placeholder: 'https://sketchfab.com/3d-models/...',
    hostnames: ['sketchfab.com', 'www.sketchfab.com'],
    defaultHeight: 520,
    allow: 'autoplay; fullscreen; xr-spatial-tracking',
  },
  {
    type: 'texlyre',
    label: 'TeXlyre',
    category: 'academic',
    description: 'Live LaTeX and Typst math rendering.',
    placeholder: 'https://texlyre.com/...',
    hostnames: ['texlyre.com', 'www.texlyre.com'],
    defaultHeight: 500,
  },
  {
    type: 'notebooklm',
    label: 'NotebookLM',
    category: 'collaboration',
    description: 'AI-grounded research environments for source material.',
    placeholder: 'https://notebooklm.google.com/...',
    hostnames: ['notebooklm.google.com'],
    defaultHeight: 560,
  },
  {
    type: 'hyperbeam',
    label: 'Hyperbeam',
    category: 'collaboration',
    description: 'Shared co-browsing sessions inside a lesson.',
    placeholder: 'https://hyperbeam.com/...',
    hostnames: ['hyperbeam.com', 'www.hyperbeam.com'],
    defaultHeight: 560,
  },
  {
    type: 'discord',
    label: 'Discord',
    category: 'collaboration',
    description: 'Course community invites and channel widgets.',
    placeholder: 'https://discord.com/invite/...',
    hostnames: ['discord.com', 'discord.gg'],
    defaultHeight: 420,
  },
] as const satisfies readonly EmbedProvider[];

export type EmbedType = (typeof EMBED_PROVIDERS)[number]['type'];

export const DEFAULT_EMBED_TYPE: EmbedType = 'youtube';

const PROVIDERS_BY_TYPE = new Map<EmbedType, EmbedProvider>(
  EMBED_PROVIDERS.map((provider) => [provider.type, provider]),
);

export function getEmbedProvider(type: EmbedType | string | null | undefined): EmbedProvider | null {
  if (!type) return null;
  return PROVIDERS_BY_TYPE.get(type as EmbedType) ?? null;
}

export function isEmbedType(type: string | null | undefined): type is EmbedType {
  return Boolean(type && PROVIDERS_BY_TYPE.has(type as EmbedType));
}
